WITH
    CTE1 AS
    (SELECT CITY, LENGTH(CITY)
    FROM STATION
    ORDER BY LENGTH(CITY) DESC, CITY
    LIMIT 1),
    CTE2 AS
    (SELECT CITY, LENGTH(CITY)
    FROM STATION
    ORDER BY LENGTH(CITY), CITY
    LIMIT 1)
SELECT *
FROM CTE1
UNION
SELECT * FROM CTE2;
