SELECT *
FROM (SELECT H.HACKER_ID AS HID, H.NAME AS HNAME, COUNT(C.CHALLENGE_ID) AS TOTCH
FROM HACKERS H
INNER JOIN CHALLENGES C ON H.HACKER_ID = C.HACKER_ID
GROUP BY H.HACKER_ID, H.NAME) A
WHERE TOTCH IN (SELECT TOTCH FROM (SELECT H.HACKER_ID AS HID, H.NAME AS HNAME, COUNT(C.CHALLENGE_ID) AS TOTCH
FROM HACKERS H
INNER JOIN CHALLENGES C ON H.HACKER_ID = C.HACKER_ID
GROUP BY H.HACKER_ID, H.NAME) B
GROUP BY TOTCH
HAVING COUNT(TOTCH) = 1) OR TOTCH = (SELECT MAX(TOTCH) FROM
(SELECT H.HACKER_ID AS HID, H.NAME AS HNAME, COUNT(C.CHALLENGE_ID) AS TOTCH
FROM HACKERS H
INNER JOIN CHALLENGES C ON H.HACKER_ID = C.HACKER_ID
GROUP BY H.HACKER_ID, H.NAME) C)
ORDER BY TOTCH DESC, HID;
