SELECT WK.ID, M.AGE, M.COINS_NEEDED, M.PWK
FROM (SELECT P.CODE AS CODE, P.AGE AS AGE, W.POWER AS PWK, MIN(W.COINS_NEEDED) AS COINS_NEEDED
      FROM WANDS W
      JOIN WANDS_PROPERTY P ON W.CODE = P.CODE
      WHERE P.IS_EVIL = 0
      GROUP BY P.CODE, P.AGE, W.POWER) M
JOIN WANDS WK ON WK.CODE = M.CODE AND WK.COINS_NEEDED = M.COINS_NEEDED AND WK.POWER = M.PWK
ORDER BY M.PWK DESC, M.AGE DESC;
