WITH
    CTE1 AS
    (SELECT S.NAME AS NAME, G.GRADE AS GRADE, S.MARKS AS MARKS, ROW_NUMBER() OVER (ORDER BY GRADE DESC, NAME ASC) AS RN, 1 AS FILT
     FROM STUDENTS S
     JOIN GRADES G ON S.MARKS BETWEEN G.MIN_MARK AND G.MAX_MARK
     WHERE G.GRADE > 7
     ORDER BY GRADE DESC, NAME ASC),
     CTE2 AS
     (SELECT NULL AS NAME, G.GRADE AS GRADE, S.MARKS AS MARKS, ROW_NUMBER() OVER (ORDER BY GRADE DESC, MARKS ASC) AS RN, 2 AS FILT
      FROM STUDENTS S
      JOIN GRADES G ON S.MARKS BETWEEN G.MIN_MARK AND G.MAX_MARK
      WHERE G.GRADE <= 7
      ORDER BY GRADE DESC, MARKS ASC)
SELECT NAME, GRADE, MARKS
FROM (SELECT * FROM CTE1
      UNION
      SELECT * FROM CTE2) CTEC
ORDER BY FILT, RN;
