SELECT H.HACKER_ID, H.NAME
FROM HACKERS H
JOIN SUBMISSIONS S ON H.HACKER_ID = S.HACKER_ID
JOIN CHALLENGES C ON (S.CHALLENGE_ID = C.CHALLENGE_ID)
JOIN DIFFICULTY D ON C.DIFFICULTY_LEVEL = D.DIFFICULTY_LEVEL
WHERE S.SCORE = D.SCORE
GROUP BY S.HACKER_ID, H.NAME
HAVING COUNT(S.CHALLENGE_ID) > 1
ORDER BY COUNT(S.CHALLENGE_ID) DESC, H.HACKER_ID;
