WITH
    DOCTOR AS
    (SELECT ROW_NUMBER() OVER (ORDER BY NAME) AS ID, NAME FROM OCCUPATIONS
    WHERE OCCUPATION = 'Doctor' ORDER BY NAME),
    PROFESSOR AS
    (SELECT ROW_NUMBER() OVER (ORDER BY NAME) AS ID, NAME FROM OCCUPATIONS
    WHERE OCCUPATION = 'Professor' ORDER BY NAME),
    SINGER AS
    (SELECT ROW_NUMBER() OVER (ORDER BY NAME) AS ID, NAME FROM OCCUPATIONS
    WHERE OCCUPATION = 'Singer' ORDER BY NAME),
    ACTOR AS
    (SELECT ROW_NUMBER() OVER (ORDER BY NAME) AS ID, NAME FROM OCCUPATIONS
    WHERE OCCUPATION = 'Actor' ORDER BY NAME)

SELECT D.NAME, P.NAME, S.NAME, A.NAME
FROM DOCTOR D
LEFT JOIN PROFESSOR P ON D.ID = P.ID
LEFT JOIN SINGER S ON D.ID = S.ID
LEFT JOIN ACTOR A ON D.ID = A.ID
UNION
SELECT D.NAME, P.NAME, S.NAME, A.NAME
FROM PROFESSOR P
LEFT JOIN DOCTOR D ON P.ID = D.ID
LEFT JOIN SINGER S ON P.ID = S.ID
LEFT JOIN ACTOR A ON P.ID = A.ID
UNION
SELECT D.NAME, P.NAME, S.NAME, A.NAME
FROM SINGER S
LEFT JOIN PROFESSOR P ON S.ID = P.ID
LEFT JOIN DOCTOR D ON S.ID = D.ID
LEFT JOIN ACTOR A ON S.ID = A.ID
UNION
SELECT D.NAME, P.NAME, S.NAME, A.NAME
FROM ACTOR A
LEFT JOIN PROFESSOR P ON A.ID = P.ID
LEFT JOIN DOCTOR D ON A.ID = D.ID
LEFT JOIN SINGER S ON A.ID = S.ID;
