-- DONE USING MSSQL
WITH
CTE1 (SUBMISSION_DATE, HACKER_ID, TOTAL, RN) AS
    (SELECT SUBMISSION_DATE, HACKER_ID, COUNT(SUBMISSION_ID),
     ROW_NUMBER() OVER (PARTITION BY SUBMISSION_DATE ORDER BY COUNT(SUBMISSION_ID) DESC, HACKER_ID)
    FROM SUBMISSIONS
    GROUP BY SUBMISSION_DATE, HACKER_ID),
CTE2 (SUBMISSION_DATE, UNIQUE_HACKER) AS
    (SELECT S1.SUBMISSION_DATE,
     (SELECT COUNT(DISTINCT HACKER_ID)
     FROM SUBMISSIONS S2
     WHERE S1.SUBMISSION_DATE = S2.SUBMISSION_DATE
     AND (S1.SUBMISSION_DATE = '2016-03-01' OR HACKER_ID IN (SELECT HACKER_ID FROM
                      (SELECT SUBMISSION_DATE, HACKER_ID
                      FROM SUBMISSIONS S3
                       WHERE S3.SUBMISSION_DATE < S1.SUBMISSION_DATE
                      GROUP BY SUBMISSION_DATE, HACKER_ID) S4 GROUP BY HACKER_ID
                      HAVING COUNT(*) = DATEDIFF(DAY, '2016-03-01', S1.SUBMISSION_DATE))))
    FROM (SELECT DISTINCT SUBMISSION_DATE AS SUBMISSION_DATE FROM SUBMISSIONS) S1)

SELECT CTE1.SUBMISSION_DATE, CTE2.UNIQUE_HACKER, H.HACKER_ID, H.NAME
FROM CTE1
INNER JOIN CTE2 ON CTE1.SUBMISSION_DATE = CTE2.SUBMISSION_DATE
INNER JOIN HACKERS H ON CTE1.HACKER_ID = H.HACKER_ID
WHERE CTE1.RN = 1;
