WITH
CTE1 AS
    (SELECT S.ID AS ID, S.NAME AS NAME, P.SALARY AS ST_SALARY
    FROM STUDENTS S
    INNER JOIN PACKAGES P ON S.ID = P.ID),
CTE2 AS
    (SELECT F.ID AS ID, F.FRIEND_ID AS FRIEND_ID, P.SALARY AS FR_SALARY
    FROM FRIENDS F
    INNER JOIN PACKAGES P ON F.FRIEND_ID = P.ID)

SELECT CTE1.NAME
FROM CTE1
INNER JOIN CTE2 ON CTE1.ID = CTE2.ID
WHERE CTE2.FR_SALARY > CTE1.ST_SALARY
ORDER BY CTE2.FR_SALARY;
