WITH
CTE1 AS
    (SELECT ROW_NUMBER() OVER (ORDER BY START_DATE) AS RN, START_DATE
    FROM PROJECTS
    WHERE START_DATE NOT IN (SELECT END_DATE FROM PROJECTS)),
CTE2 AS
    (SELECT ROW_NUMBER() OVER (ORDER BY END_DATE) AS RN, END_DATE
    FROM PROJECTS
    WHERE END_DATE NOT IN (SELECT START_DATE FROM PROJECTS))

SELECT START_DATE, END_DATE
FROM CTE1
INNER JOIN CTE2 ON CTE1.RN = CTE2.RN
ORDER BY DATEDIFF(END_DATE, START_DATE), START_DATE;
